Integration docs
divio/djangocms-internalsearch pull request #84
Opened 2019-03-15 10:28 UTC by webbyfox

2019-03-18 12:12 UTC, geoidesic requested changes

2019-03-19 10:33 UTC, monikasulik requested changes
I think ideally, you should run this by the migration team and have them try to configure a simple app and see if they manage. I reckon there's still stuff missing here.

For one thing, I don't think either here or in the README there is anything about all the django settings needed to run this app. I'm pretty sure there are some haystack settings you need to set (for example to tell it to run elastic search?).
And there's nothing about installation requirements (like having to install elastic search and which version) or about building indexes.

I think the README needs updating - both with info on how to generate the docs and more accurate info on how to install internal search. Currently, I don't think just doing what's in the README would make everything work.

Finally, I recommend checking if there's anything in Andrew's PR: https://github.com/divio/djangocms-internalsearch/pull/81/files which you want to include and closing that PR.

2019-03-20 09:53 UTC, monikasulik approved these changes

2019-03-20 09:55 UTC, geoidesic requested changes

2019-03-29 11:58 UTC, geoidesic requested changes

2019-04-01 10:58 UTC, monikasulik approved these changes

2019-04-01 11:37 UTC, merged